# Generated by Django 4.0.1 on 2022-01-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0003_book_slugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='slugs',
            new_name='slug',
        ),
    ]
